title: Vimalkumar Murugesan
logo: /asserts/profile_image.png
description: QA Automation Engineer | Selenium, Python, Jenkins | CI/CD | TestNG | Driving Quality & Efficiency in Software Development ğŸš€ | Ensuring Flawless Software Quality ğŸ› ï¸ | Streamlining Testing Processes & Enhancing Software Reliability ğŸ” | Passionate About Breaking Code & Delivering High-Quality Products ğŸ’¡ğŸ”¥
show_downloads: true
theme: jekyll-theme-minimal
